-- SQL to run in Supabase SQL Editor to create required tables.

-- Table to prevent session replay when completing signup
CREATE TABLE IF NOT EXISTS checkout_sessions_used (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id text UNIQUE,
  email text,
  created_at timestamptz DEFAULT now()
);

-- Table to record webhook-confirmed checkout completions (authoritative)
CREATE TABLE IF NOT EXISTS checkout_sessions_completed (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id text UNIQUE,
  email text,
  event_id text UNIQUE,
  raw_event jsonb,
  created_at timestamptz DEFAULT now()
);
